BOOTSTRAP_SERVER: str = "localhost:29092"
SCHEMA_REGISTRY_URL: str = "http://localhost:8081"
CORPORATE_TOPIC: str = "corporate-events"
LOBBYISM_TOPIC: str = "lobbyism-events"
CORPORATE_DETAILED_TOPIC: str = "corporate_detailed-events"
